language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: UATK4gbB2OTFSWsrwBz0EIKOQ651LARDJuBf+3OpgaDZBk651bef+Zf1cFSettkBQT4tvbuQynP/w9m/ZXrOwdGrAQxbVUkx8r8df3fPw9aEtI7cA7pMSxmcwIea+zt9tx4LyNqL16RQwcd5ZBKDgHbUWgaveazKDUubP5Nmu5TktjxYGLOL/AM5CIbBwXz4RyWnLzC3s7hQUZ+1fmJvPoKb77UZSXo2gRIYpBWrX4usVzoW5A4IY24IcVfEI/k5pEVRSALwsT9aCQkIp/w/9BrgWvcC0wgeuQy63FwoqkzdI76GlRZ9M+1wwEdeONPIdcNjze/9LaU1u/vWBmcWB3Vj8B2lHP6ICcR0C9gITS0dR4HajXhCw2JJlRcM2315qJFHh7xw8nVWf3uXwbQQ/mdoqA0hRRkGjGCStzedWf2nhHzpySkkmQDa3xeYybCuBUb2k4zil8U+3OYL3KgaKReYfufymP8jHBptLe+hFAHRQkqQ0s8vFlj72/+EObdCeHyRu9j3PLqdtGQq54dGLuV2jNlVxcYqKKJlGB3eqJyoCqzixzeiR2TBVi5kcDkVEStww51AjWRKsPCtVtP/pLjoBWyofAgskeOJvVtHCBZlL48E8IXzeX1J7Y648xj2NeACxqyr9jQJ4NQ+aTieoG7yjJunQQMytgD6zn8kB8c=
  app: fast-savannah-13472
  on:
    repo: rohinieravi/Itinerary-Saver
